'use strict';
/* Provider stages. Each stage owns its own workspace, its own honesty notices, and its own
   single primary action. Every stage of the agreed workflow is implemented, so there is no
   "planned" placeholder left to render.
   Results are loaded by app.js before render, so this module never triggers its own re-render. */
(function (root) {
  var el = root.Dom.el;
  var button = root.Dom.button;
  var C = root.Components;
  var Views = root.Views = root.Views || {};

  function gated(ctx, stageId) {
    var workflow = ctx.store.workflow();
    var brief = (workflow.brief || {}).state === 'approved';
    var materials = (workflow.materials || {}).state === 'approved';
    if (brief && materials) return null;
    var target = brief ? 'material' : 'brief';
    return C.banner('warn', 'Earlier stages must be confirmed', (brief ? 'Confirm your material selection' : 'Confirm your brief') + ' before this stage can run.', {
      actions: button(brief ? 'Go to own material' : 'Go to brief', { on: function () { ctx.navigate(root.Router.projectHref(ctx.store.snapshot().folder, target)); } })
    });
  }

  function researchSettings(ctx) {
    var project = ctx.store.project() || {};
    var saved = project.research_settings || {};
    var defaults = (ctx.store.snapshot().settings || {}).defaults || {};
    var live = saved.provider === 'anthropic';
    // There is no offline draft any more: a creative stage either reaches a provider or fails.
    var web = C.checkbox('Allow web search with citations', { checked: live ? !!saved.web_search : defaults.web_search !== false });
    var materials = C.checkbox('Share analyzed own material', { checked: live ? !!saved.include_materials : !!defaults.include_materials });
    return {
      provider: {value: 'anthropic'},
      web: web.input, materials: materials.input,
      node: el('div', { class: 'stack' }, [
        C.field('Options', el('div', { class: 'stack tight' }, [web.node, materials.node]), {
          hint: 'Research is generated by Claude. Without a provider key the stage fails rather than substituting a template.'
        })
      ])
    };
  }

  function connectionPanel(ctx) {
    var status = el('p', { class: 'metric-note', text: 'Checking the Claude connection...' });
    var test = button('Test Claude connection', { size: 'sm', on: async function () {
      test.setBusy(true, 'Testing');
      try {
        var result = await ctx.api.testResearch();
        status.textContent = (result.model || 'Claude') + ': ' + (result.message || (result.configured ? 'Configured.' : 'Not configured.'));
      } catch (error) { status.textContent = error.message; }
      finally { test.setBusy(false); }
    } });
    ctx.api.researchStatus().then(function (result) {
      status.textContent = (result.model || 'Claude') + ' | ' + (result.configured ? 'API key configured. Test the connection before generating.' : (result.error || 'API key missing. Add it in Settings.'));
    }).catch(function (error) { status.textContent = error.message; });
    return C.panel('Research connection', { children: status, footer: [test] });
  }

  /* Approval gate. A creative stage advances only on an explicit decision, and the decision names
     the exact revision it reviewed, so a later regeneration cannot inherit it. */
  function approvalPanel(ctx, stageId, record, saved) {
    if (!record || !record.revision) return null;
    var stage = root.Stages.byId(stageId) || {};
    var gate = stage.approvalStage || null;
    var project = ctx.store.project();
    var decision = gate && root.Delivery ? root.Delivery.gateDecision(project, gate) : null;
    var approved = gate ? !!(decision && decision.decision === 'approved') : record.state === 'approved';
    var needsReview = !approved;

    /* The video gates need more than a click: the manual checklist items are asserted here, and the
       subject pins the approval to the exact video that was reviewed. */
    var check = gate === 'master_video' ? readArtifact(saved, /final_check\.json$/) : null;
    var exportsManifest = gate === 'platform_adaptations' ? readArtifact(saved, /export_manifest\.json$/) : null;
    var subject = check ? check.subject : (exportsManifest ? exportsManifest.generated_at : null);
    var manual = check ? (check.checks || []).filter(function (item) { return item.mode === 'manual'; }) : [];
    var boxes = {};
    var gateNotice = null;

    if (gate === 'master_video' && check) {
      if ((check.blocking_issues || []).length) {
        gateNotice = C.banner('error', 'QC blocked this video', check.blocking_issues.join(' '));
      } else {
        gateNotice = C.banner('info', 'Confirm what no check can decide', 'The ' + manual.length + ' item(s) above are asserted when you approve, and recorded against this exact video.');
      }
    }
    if (gate === 'platform_adaptations' && exportsManifest) {
      var live = (exportsManifest.platforms || []).filter(function (item) { return item.status === 'exported'; });
      gateNotice = C.banner('info', 'Check each platform before you approve', live.length + ' export(s) are listed below with their captions and metadata.');
    }

    var feedback = C.textArea({rows: 3, placeholder: 'Optional: what should change?', ariaLabel: 'Feedback'});
    var decide = async function (decisionName, control) {
      if (control && control.setBusy) control.setBusy(true, 'Saving');
      try {
        var payload = {decision: decisionName, revision: ctx.store.revision(), feedback: feedback.value};
        if (gate) {
          payload.subject = subject;
          if (gate === 'master_video') {
            payload.confirmed = Object.keys(boxes).filter(function (id) { return boxes[id].checked; });
          }
        } else {
          payload.stage_revision = record.revision;
        }
        await ctx.api.decideStage(ctx.store.snapshot().folder, gate || stageId, payload);
        C.toast(decisionName === 'approved' ? 'Approved.' : 'Changes requested.');
      } catch (error) {
        C.toast(error.message, 'error');
      } finally {
        if (control && control.setBusy) control.setBusy(false);
        await ctx.refresh();
        ctx.rerender();
      }
    };
    var approveBtn = button(gate ? 'Approve this video' : 'Approve revision ' + record.revision, {variant: 'primary', on: function () { decide('approved', approveBtn); }});
    var changesBtn = button('Request changes', {on: function () { decide('changes_requested', changesBtn); }});

    var status = approved
      ? (gate
        ? C.banner('ok', 'Approved', 'Recorded against ' + (decision && decision.subject ? decision.subject : 'this run') + '. A new render invalidates it.')
        : C.banner('ok', 'Approved at revision ' + record.revision, 'Approving again is unnecessary unless the result changed. Any regeneration marks this stage as needing review again.'))
      : needsReview
        ? C.banner('warn', 'Review needed', 'Watch the result, then approve it or request changes. The next stage stays locked until this is approved.')
        : null;

    // The approval cannot proceed while a blocking check stands, or before the manual items are ticked.
    var blocked = !!(check && (check.blocking_issues || []).length);
    if (gate === 'master_video' && manual.length) {
      var missing = manual.filter(function (item) { return !boxes['confirm-' + item.id]; });
      void missing;
      approveBtn.disabled = blocked;
      var list = el('div', { class: 'stack tight' });
      manual.forEach(function (item) {
        var control = C.checkbox('I have done this: ' + item.label, {id: 'approve-' + item.id});
        boxes['confirm-' + item.id] = control.input;
        control.input.addEventListener('change', function () {
          var all = manual.every(function (entry) { return boxes['confirm-' + entry.id].checked; });
          approveBtn.disabled = blocked || !all;
        });
        list.append(control.node);
      });
      gateNotice = el('div', { class: 'stack tight' }, [gateNotice, list]);
      approveBtn.disabled = true;
    } else if (blocked) {
      approveBtn.disabled = true;
    }
    if (gate === 'platform_adaptations' && !exportsManifest) {
      gateNotice = C.banner('warn', 'No exports to approve', 'Generate the platform exports first.');
      approveBtn.disabled = true;
    }

    return C.panel('Approval', {
      subtitle: gate ? 'This is the gate for the finished video.' : 'Recorded against revision ' + record.revision + '.',
      children: [status || C.banner('info', 'Current state: ' + root.Stages.label(record.state), 'Generate this stage to review a result.'), gateNotice, feedback].filter(Boolean),
      footer: [changesBtn, approveBtn]
    });
  }

  /* Reads one artifact out of the loaded results, so the approval panel sees the same file the
     workspace above it is showing. */
  function readArtifact(saved, pattern) {
    var file = ((saved || {}).files || []).filter(function (item) { return pattern.test(item.path); })[0];
    if (!file || !file.content) return null;
    try { return JSON.parse(file.content); } catch (error) { return null; }
  }

  /* Preview renders are kept here rather than in the DOM, because every action ends in a refresh and
     a re-render, which would otherwise throw the player away the instant it appeared. */
  var scenePreviews = {};
  function previewKey(folder, sceneId) { return folder + '/' + sceneId; }

  function renderPreviewPlayer(holder, folder, preview) {
    C.clear(holder);
    holder.append(el('p', { class: 'metric-note', text: 'Preview: ' + preview.template + ', ' + preview.seconds + 's, ' + preview.width + 'x' + preview.height }));
    holder.append(el('video', { class: 'asset-preview', src: root.Api.projectFileUrl(folder, preview.path), attrs: { controls: 'controls', preload: 'metadata' } }));
  }

  function renderProvider(ctx, stageId) {
    var stage = root.Stages.byId(stageId);
    var state = ctx.store.snapshot();
    var body = el('div', { class: 'stack' });
    var gate = gated(ctx, stageId);
    var compose = stageId === 'compose';
    var settings = stageId === 'research' ? researchSettings(ctx) : null;
    var record = ((ctx.store.workflow().stages) || {})[stage.server];

    if (gate) body.append(gate);
    if (settings) {
      body.append(C.panel('Generation settings', { children: settings.node }));
      body.append(connectionPanel(ctx));
    }
    if (compose) {
      body.append(C.banner('info', 'This stage produces a real video', 'The composer renders final/youtube_master.mp4 with FFmpeg and inspects the file it wrote. QC decides whether the video may be approved.'));
    }
    void 0;

    var error = state.errors[stageId];
    if (error) body.append(C.banner('error', 'Last attempt failed', error + ' Any previously saved result is unchanged.'));

    var actionLabel = compose ? 'Render the video'
      : stageId === 'final' ? 'Run the final check'
        : stageId === 'exports' ? 'Generate platform exports'
          : 'Generate ' + stage.title.toLowerCase();
    var action = button(actionLabel, {
      variant: 'primary', disabled: !!gate,
      on: async function () {
        action.setBusy(true, 'Working');
        ctx.store.setError(stageId, null);
        try {
          var body2 = stageId === 'research'
            ? { provider: settings.provider.value, web_search: settings.web.checked, include_materials: settings.materials.checked }
            : {};
          await ctx.api.generate(state.folder, stage.server, body2);
          await ctx.refresh();
          await ctx.loadResults(stage.server);
          C.toast(compose ? 'The video was rendered. Watch it, then approve it below.' : stage.title + ' saved.');
        } catch (error2) {
          ctx.store.setError(stageId, error2.message);
          C.toast(error2.message, 'error');
        } finally {
          action.setBusy(false);
          ctx.rerender();
        }
      }
    });

    var saved = state.results[stage.server];
    var content = state.resultsLoading === stage.server ? C.skeleton(4)
      : (saved ? C.resultFiles(saved)
        : C.empty('No saved result loaded', 'Generate this stage, or there is nothing saved on disk yet.'));

    // The storyboard is a plan about scenes, so it gets a scene table rather than raw files.
    if (stageId === 'storyboard' && saved) {
      var sceneTable = storyboardTable(ctx, saved);
      if (sceneTable) content = sceneTable;
      // The scene table shows the narration each scene covers, so the script must be loaded too.
      if (!state.results.script && state.resultsLoading !== 'script') {
        ctx.loadResults('script').then(function () { ctx.rerender(); }).catch(function () { /* the table degrades to section ids */ });
      }
    }

    // Asset production is a list of real files, so it gets its own workspace.
    if (stageId === 'assets' && saved) {
      var assetsView = assetsWorkspace(ctx, saved);
      if (assetsView) content = assetsView;
    }

    /* The delivery stages show the video and its exports, so they get their own screens rather than a
       list of files. */
    if (stageId === 'compose' && saved) {
      var composeView = root.Delivery && root.Delivery.composeWorkspace(ctx, saved);
      if (composeView) content = composeView;
    }
    if (stageId === 'final' && saved) {
      var finalView = root.Delivery && root.Delivery.finalWorkspace(ctx, saved);
      if (finalView) content = finalView;
      // The final check quotes the QC verdict and the master, so both must be loaded to show them.
      if (!state.results.render && state.resultsLoading !== 'render') {
        ctx.loadResults('render').then(function () { ctx.rerender(); }).catch(function () { /* the screen degrades without it */ });
      }
    }
    if (stageId === 'exports' && saved) {
      var exportsView = root.Delivery && root.Delivery.exportsWorkspace(ctx, saved);
      if (exportsView) content = exportsView;
    }

    var savedSubtitle = stageId === 'storyboard' ? 'Scenes from the approved script, with own media selected where it fits.'
      : stageId === 'assets' ? 'What was actually produced, and what is still missing.'
        : stageId === 'compose' ? 'The video that was rendered, and what QC measured in it.'
          : stageId === 'final' ? 'The finished video, its thumbnail and the checks around it.'
            : stageId === 'exports' ? 'One file per platform, ready to upload.'
              : 'Files written into the project folder.';
    body.append(C.panel('Saved result', {
      subtitle: savedSubtitle,
      actions: action,
      children: content
    }));

    var approval = approvalPanel(ctx, stageId, record, saved);
    if (approval) body.append(approval);
    return body;
  }

  /* Narration, produced footage, and what is still missing. Every row is a real file or a real gap. */
  function assetsWorkspace(ctx, saved) {
    var file = (saved.files || []).filter(item => /asset_manifest\.json$/.test(item.path))[0];
    if (!file || !file.content) return null;
    var manifest;
    try { manifest = JSON.parse(file.content); } catch (error) { return null; }

    var wrap = el('div', { class: 'stack' });
    (manifest.warnings || []).forEach(function (warning) { wrap.append(C.banner('warn', 'Asset production', warning)); });

    var narration = manifest.narration || {};
    var counts = manifest.counts || {};
    wrap.append(C.metrics([
      {label: 'Narration sections', value: String(narration.produced || 0), numeric: true, note: (narration.total_seconds ? narration.total_seconds.toFixed(1) + 's of audio' : 'no audio')},
      {label: 'Own media used', value: String(counts.own_media || 0), numeric: true},
      {label: 'Produced here', value: String(counts.produced || 0), numeric: true},
      {label: 'Still missing', value: String(counts.still_missing || 0), numeric: true},
      {label: 'Rights blocked', value: String(counts.rights_blocked || 0), numeric: true, note: (counts.rights_blocked ? 'cannot be rendered' : 'all clear')}
    ]));
    wrap.append(C.banner(manifest.status === 'complete' ? 'ok' : 'warn',
      manifest.status === 'complete' ? 'Every scene has media and the narration is ready' : 'This project is not ready to compose',
      manifest.status === 'complete' ? 'The composer has real media and audio to work with.' : 'Scenes without media would render as blank frames, and scenes with unrecorded rights cannot be rendered at all, so composition stays blocked until each is resolved.'));

    /* Which sources were searched, and the reason each one that was not could not be. A missing
       source is a stated cause, never an unexplained absence of footage. */
    var sourcing = manifest.sourcing;
    if (sourcing) {
      var sourcingRows = el('div', { class: 'stack tight' });
      (sourcing.sources || []).forEach(function (item) {
        sourcingRows.append(el('p', { class: 'metric-note', text: 'Searched: ' + item.short + ' (' + (item.media_kinds || []).join(', ') + ')' }));
      });
      (sourcing.unavailable || []).forEach(function (item) {
        sourcingRows.append(el('p', { class: 'field-error', text: 'Not searched: ' + item.short + ' — ' + item.reason }));
      });
      if (!(sourcing.sources || []).length && !(sourcing.unavailable || []).length) sourcingRows.append(el('p', { class: 'metric-note', text: 'No media source was consulted.' }));
      wrap.append(C.panel('Where the media came from', {
        subtitle: 'Free-licence sources are tried in order. A source that could not be used says why.',
        children: sourcingRows
      }));
    }

    // Narration
    var narrationSections = (narration.sections || []);
    if (narrationSections.length) {
      var narrationPanel = el('div', { class: 'stack' });
      narrationSections.forEach(function (section) {
        var row = el('div', { class: 'stack tight' });
        var heading = el('div', { class: 'row between' }, [
          el('strong', { text: section.title || section.section_id }),
          C.pill(section.status === 'done' ? 'approved' : (section.status === 'failed' ? 'failed' : 'review'))
        ]);
        row.append(heading);
        if (section.status === 'done') {
          row.append(el('p', { class: 'metric-note', text: [section.duration_seconds ? section.duration_seconds.toFixed(1) + 's' : 'duration unknown', section.characters + ' characters', section.model, section.voice].filter(Boolean).join(' | ') }));
          row.append(el('audio', { class: 'asset-preview-audio', src: root.Api.projectFileUrl(ctx.store.snapshot().folder, section.path), attrs: {controls: 'controls', preload: 'none'}, props: {style: 'width:100%'} }));
        } else {
          row.append(el('p', { class: 'field-error', text: section.reason || 'No audio was produced for this section.' }));
        }
        narrationPanel.append(row);
      });
      wrap.append(C.panel('Narration', { subtitle: 'One audio file per script section, with the duration measured from the file itself.', children: narrationPanel }));
    }

    // Scenes
    var table = el('table', { class: 'table' });
    table.append(el('thead', {}, el('tr', {}, [el('th', { text: 'Scene' }), el('th', { text: 'Media' }), el('th', { text: 'Source' })])));
    var body2 = el('tbody');
    (manifest.scenes || []).forEach(function (scene) {
      var pill = scene.status === 'own_media' ? C.pill('approved')
        : scene.status === 'produced' ? C.pill('ok')
          : scene.status === 'failed' ? C.pill('failed') : C.pill('review');
      var sourceCell;
      // The rights verdict travels with the scene, so the interface shows the real decision.
      var rightsState = scene.rights_state || null;
      var rightsLines = [];
      if (rightsState) {
        if (rightsState.state === 'blocked') rightsLines.push(el('p', { class: 'field-error', text: (rightsState.reasons || [])[0] || 'Rights are not cleared for this scene.' }));
        else if (rightsState.attribution) rightsLines.push(el('p', { class: 'metric-note', text: 'Credit: ' + rightsState.attribution }));
        else rightsLines.push(el('p', { class: 'metric-note', text: 'Rights: ' + (rightsState.short || 'cleared') }));
      }
      if (scene.status === 'own_media') {
        sourceCell = el('div', { class: 'stack tight' }, [el('p', { class: 'metric-note', text: 'Your own material' })].concat(rightsLines));
      } else if (scene.status === 'produced') {
        sourceCell = el('div', { class: 'stack tight' }, [
          el('p', { class: 'metric-note', text: (scene.clip.provider || 'stock') + (scene.clip.author ? ' | ' + scene.clip.author : '') + (scene.clip.media_kind === 'image' ? ' | still image' : '') }),
          el('p', { class: 'metric-note', text: scene.clip.licence || '' })
        ].concat(rightsLines).concat([
          scene.clip.source_url ? el('a', { class: 'mono', href: scene.clip.source_url, text: 'Source clip', attrs: {target: '_blank', rel: 'noopener noreferrer'}}) : null
        ]));
      } else sourceCell = el('p', { class: 'field-error', text: scene.reason || 'Nothing was produced for this scene.' });
      body2.append(el('tr', {}, [
        el('td', {}, [el('strong', { text: scene.title || scene.scene_id }), el('p', { class: 'metric-note mono', text: scene.scene_id })]),
        el('td', {}, [pill, el('p', { class: 'metric-note', text: scene.seconds ? scene.seconds + 's needed' : '' })]),
        el('td', {}, sourceCell)
      ]));
    });
    table.append(body2);
    wrap.append(C.panel('Scenes', { children: table, class: 'flush' }));

    var details = el('details');
    details.append(el('summary', { text: 'Supporting files' }));
    details.append(C.resultFiles(saved));
    wrap.append(details);
    return wrap;
  }

  /* Reads the storyboard artifact and renders each scene with its narration, chosen own media, and
     the generation prompt that stands in when nothing available fits. */
  function storyboardTable(ctx, saved) {
    var file = (saved.files || []).filter(item => /storyboard\.json$/.test(item.path))[0];
    if (!file || !file.content) return null;
    var parsed;
    try { parsed = JSON.parse(file.content); } catch (error) { return null; }
    var scenes = Array.isArray(parsed.scenes) ? parsed.scenes : [];
    if (!scenes.length) return null;

    var library = {};
    ctx.store.snapshot().library.forEach(function (asset) { library[asset.id] = asset; });
    var scripts = ctx.store.snapshot().results.script;
    var narration = {};
    if (scripts) {
      var scriptFile = (scripts.files || []).filter(item => /script\.json$/.test(item.path))[0];
      if (scriptFile && scriptFile.content) {
        try {
          JSON.parse(scriptFile.content).sections.forEach(function (section) { narration[section.id] = section; });
        } catch (error) { /* leave narration empty */ }
      }
    }

    var wrap = el('div', { class: 'stack' });
    if (parsed.warnings && parsed.warnings.length) {
      parsed.warnings.forEach(function (warning) { wrap.append(C.banner('warn', 'Storyboard warning', warning)); });
    }

    /* The prompt pack and the template vocabulary, so the fill column and the panel below it use the
       server's own names rather than a list invented here. */
    var packFile = (saved.files || []).filter(function (item) { return /scene_prompts\.json$/.test(item.path); })[0];
    var pack = null;
    if (packFile && packFile.content) { try { pack = JSON.parse(packFile.content); } catch (error) { pack = null; } }
    var promptsById = {};
    if (pack && Array.isArray(pack.prompts)) pack.prompts.forEach(function (item) { promptsById[item.scene_id] = item; });
    var templates = ((ctx.store.snapshot().renderTemplates || {}).templates) || [];
    var profiles = (pack && pack.profiles) || ((ctx.store.snapshot().renderTemplates || {}).profiles) || {};

    /* Explicit pills rather than the workflow-state ones: a scene waiting to be filled is not
       "failed", and saying so would be wrong. */
    function statePill(tone, text) { return el('span', { class: 'pill ' + tone, text: text }); }

    function fillCell(scene) {
      if (scene.asset_id) {
        var asset = library[scene.asset_id];
        var attached = scene.attachment;
        return el('div', { class: 'stack tight' }, [
          statePill('ok', attached ? 'Attached' : 'Media'),
          el('p', { class: 'metric-note', text: attached ? 'Attached: ' + (asset ? asset.name : scene.asset_id) : (asset ? asset.name : 'Asset ' + scene.asset_id) }),
          attached && attached.provider ? el('p', { class: 'metric-note', text: 'from ' + attached.provider }) : null
        ]);
      }
      if (scene.graphic_template) {
        return el('div', { class: 'stack tight' }, [
          statePill('info', 'Local'),
          el('p', { class: 'metric-note', text: 'Drawn locally: ' + scene.graphic_template })
        ]);
      }
      var prompt = promptsById[scene.id];
      return el('div', { class: 'stack tight' }, [
        statePill('review', 'To fill'),
        el('p', { class: 'metric-note', text: prompt ? (prompt.typographic ? 'Mostly on-screen text' : 'Needs footage') : 'Nothing assigned yet' })
      ]);
    }

    var missing = scenes.filter(function (scene) { return !scene.asset_id; });
    wrap.append(C.metrics([
      {label: 'Scenes', value: String(scenes.length), numeric: true},
      {label: 'Using own media', value: String(scenes.length - missing.length), numeric: true},
      {label: 'Still to produce', value: String(missing.length), numeric: true},
      {label: 'Total', value: (parsed.total_duration_seconds || 0) + 's', numeric: true}
    ]));

    var table = el('table', { class: 'table' });
    table.append(el('thead', {}, el('tr', {}, [
      el('th', { text: 'Scene' }), el('th', { text: 'Narration' }), el('th', { text: 'Own media' }), el('th', { text: 'Visual' }), el('th', { text: 'Fill' })
    ])));
    var body2 = el('tbody');
    scenes.forEach(function (scene) {
      var asset = scene.asset_id ? library[scene.asset_id] : null;
      var section = scene.narration_section_id ? narration[scene.narration_section_id] : null;
      var narrationCell = el('div', { class: 'stack tight' }, [
        el('p', { class: 'metric-note', text: section ? String(section.narration || '').slice(0, 220) : (scene.narration_section_id ? 'Section ' + scene.narration_section_id : 'No narration section linked') })
      ]);
      if (section) narrationCell.append(el('span', { class: 'pill', text: section.title || scene.narration_section_id }));

      var mediaCell = scene.asset_id
        ? el('div', { class: 'stack tight' }, [
            el('span', { class: 'pill ok', text: 'Own media' }),
            el('p', { class: 'metric-note', text: asset ? asset.name : 'Asset ' + scene.asset_id })
          ])
        : el('div', { class: 'stack tight' }, [
            el('span', { class: 'pill review', text: 'Missing' }),
            el('p', { class: 'metric-note', text: scene.generation_prompt ? 'Prompt ready for asset production.' : 'No generation prompt was written for this scene.' })
          ]);

      var visualCell = el('div', { class: 'stack tight' }, [
        el('p', { class: 'metric-note', text: scene.visual_intent || '' })
      ]);
      var meta = [scene.shot_type, scene.seconds ? scene.seconds + 's' : null, scene.transition].filter(Boolean).join(' | ');
      if (meta) visualCell.append(el('span', { class: 'metric-note', text: meta }));
      if (scene.on_screen_text) visualCell.append(el('span', { class: 'metric-note', text: 'On screen: ' + scene.on_screen_text }));
      if (!scene.asset_id && scene.generation_prompt) visualCell.append(el('div', { class: 'asset-excerpt', text: scene.generation_prompt }));

      body2.append(el('tr', {}, [
        el('td', {}, [el('strong', { text: scene.title }), el('p', { class: 'metric-note mono', text: scene.id })]),
        el('td', {}, narrationCell),
        el('td', {}, mediaCell),
        el('td', {}, visualCell),
        el('td', {}, fillCell(scene))
      ]));
    });
    table.append(body2);
    wrap.append(table);

    /* Filling a scene, per scene. Progressive disclosure keeps fourteen of these readable: each one
       is a disclosure that stays closed until it is needed. */
    var fillStack = el('div', { class: 'stack tight' });
    if (!missing.length) {
      fillStack.append(el('p', { class: 'metric-note', text: 'Every scene already has own media or a local template.' }));
    }
    missing.forEach(function (scene) { fillStack.append(fillEditor(scene)); });
    wrap.append(C.panel('Fill each scene', {
      subtitle: 'Draw it locally, generate it elsewhere and attach it, or let asset production look for footage. Nothing here spends money.',
      children: fillStack
    }));

    function runWith(control, label, work) {
      if (control && control.setBusy) control.setBusy(true, label);
      return Promise.resolve()
        .then(work)
        .catch(function (error) { C.toast(error.message, 'error'); })
        .then(function () { if (control && control.setBusy) control.setBusy(false); })
        .then(function () { return ctx.refresh(); })
        // The saved result is cached, so an edit would otherwise leave the old plan on screen.
        .then(function () { return ctx.loadResults('storyboard'); })
        .then(function () { ctx.rerender(); })
        .catch(function (error) { C.toast(error.message, 'error'); });
    }

    function fillEditor(scene) {
      var entry = promptsById[scene.id] || {};
      var folder = ctx.store.snapshot().folder;
      var assigned = scene.graphic_template || null;
      var detail = el('details', { class: 'fill-scene' });
      detail.append(el('summary', {}, [
        el('strong', { text: scene.title || scene.id }),
        el('span', { class: 'metric-note', text: ' ' + (scene.seconds || 0) + 's' }),
        assigned ? statePill('info', 'Local: ' + assigned) : statePill('review', 'Not filled'),
        entry.typographic ? el('span', { class: 'metric-note', text: ' · mostly on-screen text' }) : null
      ]));
      var body = el('div', { class: 'stack tight' });
      detail.append(body);

      var promptText = entry.prompt || scene.generation_prompt || '';
      body.append(el('div', { class: 'row between' }, [
        el('strong', { text: 'Prompt for a generation tool' }),
        button('Copy prompt', { size: 'sm', on: function () {
          C.copyText(promptText).then(function (how) { if (how === 'copied') C.toast('Prompt copied.'); });
        } })
      ]));
      body.append(el('div', { class: 'asset-excerpt', text: promptText || 'The storyboard wrote no prompt for this scene.' }));

      if (entry.typographic) {
        body.append(C.banner('warn', 'Mostly on-screen text',
          'A video generator will misspell these words or invent ones that are not in your script. Drawing it locally spells them exactly.'));
      }

      var profileKeys = Object.keys(profiles);
      if (profileKeys.length) {
        var toolSelect = C.select({ id: 'tool-' + scene.id, value: (pack && pack.provider) || 'manual' }, profileKeys.map(function (key) {
          return { value: key, label: profiles[key].short };
        }));
        var notes = el('ul', { class: 'notes' });
        function renderNotes() {
          C.clear(notes);
          var profile = profiles[toolSelect.value] || {};
          (profile.notes || []).forEach(function (note) { notes.append(el('li', { text: note })); });
        }
        toolSelect.addEventListener('change', renderNotes);
        renderNotes();
        body.append(C.field('Where you will generate it', toolSelect, { hint: 'The notes change with the tool. The prompt never does.' }));
        body.append(notes);
      }

      // --- draw it locally ---
      var templateSelect = C.select({ id: 'template-' + scene.id, value: assigned || entry.suggested_template || templates[0] }, templates.map(function (name) {
        return { value: name, label: name };
      }));
      var dataBox = C.textArea({ id: 'data-' + scene.id, rows: 4, placeholder: 'The data this template needs, as JSON.' });
      dataBox.value = scene.graphic_data ? JSON.stringify(scene.graphic_data, null, 2) : '';
      var previewHolder = el('div');

      var assign = button(assigned ? 'Save template and data' : 'Draw with this template', { size: 'sm', variant: 'primary', on: function () {
        var data = null;
        var raw = String(dataBox.value || '').trim();
        if (raw) {
          try { data = JSON.parse(raw); }
          catch (error) { C.toast('The data is not valid JSON: ' + error.message, 'error'); return; }
        }
        runWith(assign, 'Saving', function () {
          return ctx.api.assignGraphic(folder, scene.id, templateSelect.value, data).then(function (result) {
            if (result.artifact.needs_data) C.toast('Template saved. It still needs data: ' + result.artifact.data_problem, 'error');
            else C.toast('This scene will be drawn as ' + templateSelect.value + '.');
          });
        });
      } });
      var clear = button('Clear', { size: 'sm', disabled: !assigned, on: function () {
        runWith(clear, 'Clearing', function () {
          return ctx.api.assignGraphic(folder, scene.id, null).then(function () { C.toast('Cleared. Asset production will look for footage instead.'); });
        });
      } });
      var preview = button('Render preview', { size: 'sm', on: function () {
        var data = null;
        var raw = String(dataBox.value || '').trim();
        if (raw) { try { data = JSON.parse(raw); } catch (error) { C.toast('The data is not valid JSON: ' + error.message, 'error'); return; } }
        runWith(preview, 'Drawing', function () {
          return ctx.api.renderPreview(folder, scene.id, { template: templateSelect.value, data: data }).then(function (result) {
            scenePreviews[previewKey(folder, scene.id)] = result.preview;
            renderPreviewPlayer(previewHolder, folder, result.preview);
            C.toast('Preview drawn. It is not part of the plan until you save the template.');
          });
        });
      } });
      var storedPreview = scenePreviews[previewKey(folder, scene.id)];
      if (storedPreview) renderPreviewPlayer(previewHolder, folder, storedPreview);
      body.append(C.field('Draw it locally instead', templateSelect, { hint: 'A drawing is free, offline, and spells your words exactly. Assigning changes the storyboard, so it needs approval again.' }));
      body.append(C.field('Data for that template', dataBox, { hint: 'Assigning fills in a starting point where one can be derived; nothing is invented. A chart needs real figures.' }));
      body.append(el('div', { class: 'row' }, [assign, preview, clear]));
      body.append(previewHolder);

      // --- attach something generated elsewhere ---
      var eligible = ctx.store.snapshot().library.filter(function (asset) {
        return asset.publishable !== false && C.rightsState(asset).state !== 'blocked';
      });
      var attachSelect = C.select({ id: 'attach-' + scene.id, value: eligible.length ? eligible[0].id : '' }, eligible.map(function (asset) {
        return { value: asset.id, label: asset.name };
      }));
      var attachBtn = button('Attach to this scene', { size: 'sm', disabled: !eligible.length, on: function () {
        runWith(attachBtn, 'Attaching', function () {
          return ctx.api.attachSceneAsset(folder, scene.id, { asset_id: attachSelect.value }).then(function () { C.toast('Attached.'); });
        });
      } });
      body.append(C.field('Use material already in the library', attachSelect, { hint: eligible.length ? 'Only material whose rights are recorded is offered.' : 'Nothing in the library is rights-cleared yet. Record rights on an item first.' }));
      body.append(el('div', { class: 'row' }, [attachBtn]));

      var fileInput = el('input', { type: 'file', id: 'attach-file-' + scene.id, attrs: { 'aria-label': 'Choose a generated file to attach' } });
      fileInput.addEventListener('change', function (event) {
        var chosen = (event.target.files || [])[0];
        if (!chosen) return;
        event.target.value = '';
        runWith(fileInput, 'Uploading', function () {
          return ctx.api.upload(chosen, 'media').then(function (uploaded) {
            var assetId = uploaded.asset.id;
            // Rights are recorded before attaching, because the gate will refuse an unrecorded file.
            return new Promise(function (resolve) {
              C.rightsDialog({
                subject: chosen.name,
                licences: ctx.store.snapshot().licences || [],
                rights: { basis: 'generated' },
                onSave: function (rights) {
                  return ctx.api.setAssetRights(assetId, rights).then(function () {
                    return ctx.api.attachSceneAsset(folder, scene.id, { asset_id: assetId, tool: rights.holder, note: rights.note });
                  }).then(function () { C.toast('Uploaded, recorded and attached to ' + scene.id + '.'); resolve(true); });
                },
                onCancel: function () { C.toast('The file is in the library but was not attached.', 'error'); resolve(false); }
              });
            });
          });
        });
      });
      body.append(C.field('Or upload a file you generated', fileInput, { hint: 'Uploading here asks for its licence basis first, because attaching an unrecorded file would be refused.' }));

      // --- generate it here, through Comfy ---
      body.append(comfyPanel(ctx, scene));

      return detail;
    }

    var details = el('details');
    details.append(el('summary', { text: 'Supporting files' }));
    details.append(C.resultFiles(saved));
    wrap.append(details);
    return wrap;
  }

  /* Generating a scene through Comfy, offered beside the other two ways of filling one.
     The job runs on the server, so leaving the screen does not cancel it and coming back re-attaches. */
  function comfyPanel(ctx, scene) {
    var folder = ctx.store.snapshot().folder;
    var wrap = el('div', { class: 'stack' });
    var statusLine = el('p', { class: 'metric-note', text: 'Checking Comfy...' });
    var controls = el('div', { class: 'stack' });
    var provider = null;
    var generation = null;
    var timer = null;
    var cancelled = false;

    var prompt = C.textArea({ id: 'comfy-prompt-' + scene.id, rows: 3, placeholder: 'Describe the shot for the generator.' });
    prompt.value = scene.generation_prompt || scene.visual_intent || '';
    var workflowSelect = null;

    function stopWatching() { cancelled = true; if (timer) { clearTimeout(timer); timer = null; } }

    function paint() {
      controls.replaceChildren();
      if (!provider) { statusLine.textContent = 'Checking Comfy...'; return; }
      if (!provider.configured) {
        statusLine.textContent = 'Comfy is not configured, so nothing can be generated here.';
        controls.append(C.banner('warn', 'Add a Comfy API key to generate a scene',
          'Settings stores the key; the workflow you export from ComfyUI goes in ' + (provider.workflow_config_path || 'projects/_settings/comfy/workflows.json') + '. Without it, use a local template, stock sourcing, or attach a file you generated elsewhere.'));
        return;
      }
      /* The key and the workflow are two different things. A config that names a workflow file which
         is not there is not a working setup, so it must not offer a generation it cannot deliver. */
      if (!provider.workflow_ready) {
        statusLine.textContent = 'Comfy has no usable workflow, so nothing can be generated here.';
        controls.append(C.banner('warn', 'No exported workflow is in place',
          provider.workflow_problem || 'Export your ComfyUI workflow with Workflow then Export (API) and save it beside workflows.json.'));
        return;
      }
      if (!provider.workflows || !provider.workflows.length) {
        statusLine.textContent = 'No Comfy workflow is configured, so nothing can be generated here.';
        controls.append(C.banner('warn', 'No workflow is configured', provider.workflow_problem || 'Add workflows.json beside your exported API workflow.'));
        return;
      }

      var running = generation && generation.active ? generation.active : null;

      if (running) {
        statusLine.textContent = 'Generating with ' + running.workflow + ': ' + root.Stages.label(running.status)
          + (running.progress && typeof running.progress.value === 'number' ? ' (' + Math.round(running.progress.value * 100) + '%)' : '')
          + '. This continues if you leave the page.';
        var cancelBtn = button('Cancel the generation', { on: function () {
          cancelBtn.setBusy(true, 'Cancelling');
          ctx.api.cancelGeneration(folder, scene.id, running.job_id).then(function () { return refresh(); })
            .catch(function (error) { C.toast(error.message, 'error'); })
            .finally(function () { cancelBtn.setBusy(false); });
        } });
        controls.append(el('div', { class: 'row' }, [cancelBtn]));
        return;
      }

      // A finished job updates the scene through the server, so the view only has to reload it.
      if (generation && generation.imported_asset_id) {
        statusLine.textContent = 'A generated file is attached to this scene.';
      } else if (generation && generation.last_error) {
        statusLine.textContent = 'The last generation did not produce a file.';
        controls.append(C.banner('warn', 'The last generation failed', generation.last_error));
      } else if (scene.asset_id || scene.graphic_template) {
        statusLine.textContent = scene.asset_id
          ? 'This scene already has own media, so generating would replace it. Detach it first.'
          : 'This scene is drawn locally by a template, which is free. Clear that first to generate instead.';
        return;
      } else {
        statusLine.textContent = 'Nothing has been generated for this scene yet.';
      }

      if (scene.asset_id || scene.graphic_template) return;

      workflowSelect = C.select({ id: 'comfy-workflow-' + scene.id, value: provider.default_workflow || provider.workflows[0].name },
        provider.workflows.map(function (item) { return { value: item.name, label: item.name + ' (' + item.output + ')' + (item.exists ? '' : ' - file missing') }; }));

      var generateBtn = button('Generate this scene', { variant: 'primary', on: function () {
        generateBtn.setBusy(true, 'Submitting');
        ctx.api.generateScene(folder, scene.id, { workflow: workflowSelect.value, prompt: prompt.value }).then(function (result) {
          C.toast('Generation submitted. It costs Comfy credits and takes a few minutes.');
          generation = { active: { job_id: result.job.job_id, status: result.job.status, workflow: result.job.workflow, progress: null } };
          paint();
          watch(result.job.job_id);
        }).catch(function (error) {
          C.toast(error.message, 'error');
          paint();
        }).finally(function () { generateBtn.setBusy(false); });
      } });

      controls.append(C.field('Workflow', workflowSelect, { hint: 'Each one is a workflow you exported from ComfyUI. Video uses more credits than an image.' }));
      controls.append(C.field('Prompt', prompt, { hint: 'Sent to the node named in workflows.json. Edit it here without changing the storyboard.' }));
      controls.append(el('div', { class: 'row' }, [generateBtn]));
      controls.append(el('p', { class: 'metric-note', text: 'A run costs Comfy credits and takes minutes. The result is imported as your own generated work and attached to this scene.' }));
    }

    /* Polls the server, which polls Comfy. The cadence is deliberately slow: a GPU job runs for
       minutes and does not need to be asked about every second. */
    function watch(jobId) {
      if (cancelled) return;
      ctx.api.generationStatus(folder, scene.id, jobId).then(function (result) {
        if (cancelled) return;
        var job = result.job || {};
        generation = { active: result.done ? null : { job_id: jobId, status: job.status, workflow: job.workflow, progress: job.progress }, imported_asset_id: result.attached_asset_id || generation && generation.imported_asset_id, last_error: job.error || null };
        if (result.attached_asset_id) {
          C.toast('The scene was generated and attached.');
          ctx.loadResults('storyboard').then(function () { ctx.rerender(); });
          return;
        }
        if (result.done) { paint(); return; }
        paint();
        timer = setTimeout(function () { watch(jobId); }, 4000);
      }).catch(function (error) {
        if (cancelled) return;
        statusLine.textContent = error.message;
        generatorError(error);
      });
    }

    function generatorError(error) { C.toast(error.message, 'error'); }

    function refresh() {
      return ctx.api.sceneGeneration(folder, scene.id).then(function (result) {
        provider = result.comfy;
        generation = result.generation;
        paint();
        if (generation && generation.active) watch(generation.active.job_id);
      }).catch(function (error) { statusLine.textContent = error.message; });
    }

    wrap.append(statusLine);
    wrap.append(controls);
    refresh();
    ctx.onLeave = stopWatching;
    return wrap;
  }
  function render(ctx, stageId) {
    return renderProvider(ctx, stageId);
  }

  Views.stage = {
    render: render,
    meta: function (stageId) {
      var stage = root.Stages.byId(stageId);
      return {
        title: stage.title,
        eyebrow: 'Stage ' + (root.Stages.indexOf(stageId) + 1) + ' of ' + root.Stages.STAGES.length,
        subtitle: stage.summary
      };
    }
  };
})(window);