'use strict';
/* Provider stages. Each stage owns its own workspace, its own honesty notices, and its own
   single primary action. Every stage of the agreed workflow is implemented, so there is no
   "planned" placeholder left to render.
   Results are loaded by app.js before render, so this module never triggers its own re-render. */
(function (root) {
  var el = root.Dom.el;
  var button = root.Dom.button;
  var C = root.Components;
  var Views = root.Views = root.Views || {};

  function gated(ctx, stageId) {
    var workflow = ctx.store.workflow();
    var brief = (workflow.brief || {}).state === 'approved';
    var materials = (workflow.materials || {}).state === 'approved';
    if (brief && materials) return null;
    var target = brief ? 'material' : 'brief';
    return C.banner('warn', 'Earlier stages must be confirmed', (brief ? 'Confirm your material selection' : 'Confirm your brief') + ' before this stage can run.', {
      actions: button(brief ? 'Go to own material' : 'Go to brief', { on: function () { ctx.navigate(root.Router.projectHref(ctx.store.snapshot().folder, target)); } })
    });
  }

  function researchSettings(ctx) {
    var project = ctx.store.project() || {};
    var saved = project.research_settings || {};
    var defaults = (ctx.store.snapshot().settings || {}).defaults || {};
    var live = saved.provider === 'anthropic';
    // There is no offline draft any more: a creative stage either reaches a provider or fails.
    var web = C.checkbox('Allow web search with citations', { checked: live ? !!saved.web_search : defaults.web_search !== false });
    var materials = C.checkbox('Share analyzed own material', { checked: live ? !!saved.include_materials : !!defaults.include_materials });
    return {
      provider: {value: 'anthropic'},
      web: web.input, materials: materials.input,
      node: el('div', { class: 'stack' }, [
        C.field('Options', el('div', { class: 'stack tight' }, [web.node, materials.node]), {
          hint: 'Research is generated by Claude. Without a provider key the stage fails rather than substituting a template.'
        })
      ])
    };
  }

  function connectionPanel(ctx) {
    var status = el('p', { class: 'metric-note', text: 'Checking the Claude connection...' });
    var test = button('Test Claude connection', { size: 'sm', on: async function () {
      test.setBusy(true, 'Testing');
      try {
        var result = await ctx.api.testResearch();
        status.textContent = (result.model || 'Claude') + ': ' + (result.message || (result.configured ? 'Configured.' : 'Not configured.'));
      } catch (error) { status.textContent = error.message; }
      finally { test.setBusy(false); }
    } });
    ctx.api.researchStatus().then(function (result) {
      status.textContent = (result.model || 'Claude') + ' | ' + (result.configured ? 'API key configured. Test the connection before generating.' : (result.error || 'API key missing. Add it in Settings.'));
    }).catch(function (error) { status.textContent = error.message; });
    return C.panel('Research connection', { children: status, footer: [test] });
  }

  /* Approval gate. A creative stage advances only on an explicit decision, and the decision names
     the exact revision it reviewed, so a later regeneration cannot inherit it. */
  function approvalPanel(ctx, stageId, record, saved) {
    if (!record || !record.revision) return null;
    var stage = root.Stages.byId(stageId) || {};
    var gate = stage.approvalStage || null;
    var project = ctx.store.project();
    var decision = gate && root.Delivery ? root.Delivery.gateDecision(project, gate) : null;
    var approved = gate ? !!(decision && decision.decision === 'approved') : record.state === 'approved';
    var needsReview = !approved;

    /* The video gates need more than a click: the manual checklist items are asserted here, and the
       subject pins the approval to the exact video that was reviewed. */
    var check = gate === 'master_video' ? readArtifact(saved, /final_check\.json$/) : null;
    var exportsManifest = gate === 'platform_adaptations' ? readArtifact(saved, /export_manifest\.json$/) : null;
    var subject = check ? check.subject : (exportsManifest ? exportsManifest.generated_at : null);
    var manual = check ? (check.checks || []).filter(function (item) { return item.mode === 'manual'; }) : [];
    var boxes = {};
    var gateNotice = null;

    if (gate === 'master_video' && check) {
      if ((check.blocking_issues || []).length) {
        gateNotice = C.banner('error', 'QC blocked this video', check.blocking_issues.join(' '));
      } else {
        gateNotice = C.banner('info', 'Confirm what no check can decide', 'The ' + manual.length + ' item(s) above are asserted when you approve, and recorded against this exact video.');
      }
    }
    if (gate === 'platform_adaptations' && exportsManifest) {
      var live = (exportsManifest.platforms || []).filter(function (item) { return item.status === 'exported'; });
      gateNotice = C.banner('info', 'Check each platform before you approve', live.length + ' export(s) are listed below with their captions and metadata.');
    }

    var feedback = C.textArea({rows: 3, placeholder: 'Optional: what should change?', ariaLabel: 'Feedback'});
    var decide = async function (decisionName, control) {
      if (control && control.setBusy) control.setBusy(true, 'Saving');
      try {
        var payload = {decision: decisionName, revision: ctx.store.revision(), feedback: feedback.value};
        if (gate) {
          payload.subject = subject;
          if (gate === 'master_video') {
            payload.confirmed = Object.keys(boxes).filter(function (id) { return boxes[id].checked; });
          }
        } else {
          payload.stage_revision = record.revision;
        }
        await ctx.api.decideStage(ctx.store.snapshot().folder, gate || stageId, payload);
        C.toast(decisionName === 'approved' ? 'Approved.' : 'Changes requested.');
      } catch (error) {
        C.toast(error.message, 'error');
      } finally {
        if (control && control.setBusy) control.setBusy(false);
        await ctx.refresh();
        ctx.rerender();
      }
    };
    var approveBtn = button(gate ? 'Approve this video' : 'Approve revision ' + record.revision, {variant: 'primary', on: function () { decide('approved', approveBtn); }});
    var changesBtn = button('Request changes', {on: function () { decide('changes_requested', changesBtn); }});

    var status = approved
      ? (gate
        ? C.banner('ok', 'Approved', 'Recorded against ' + (decision && decision.subject ? decision.subject : 'this run') + '. A new render invalidates it.')
        : C.banner('ok', 'Approved at revision ' + record.revision, 'Approving again is unnecessary unless the result changed. Any regeneration marks this stage as needing review again.'))
      : needsReview
        ? C.banner('warn', 'Review needed', 'Watch the result, then approve it or request changes. The next stage stays locked until this is approved.')
        : null;

    // The approval cannot proceed while a blocking check stands, or before the manual items are ticked.
    var blocked = !!(check && (check.blocking_issues || []).length);
    if (gate === 'master_video' && manual.length) {
      var missing = manual.filter(function (item) { return !boxes['confirm-' + item.id]; });
      void missing;
      approveBtn.disabled = blocked;
      var list = el('div', { class: 'stack tight' });
      manual.forEach(function (item) {
        var control = C.checkbox('I have done this: ' + item.label, {id: 'approve-' + item.id});
        boxes['confirm-' + item.id] = control.input;
        control.input.addEventListener('change', function () {
          var all = manual.every(function (entry) { return boxes['confirm-' + entry.id].checked; });
          approveBtn.disabled = blocked || !all;
        });
        list.append(control.node);
      });
      gateNotice = el('div', { class: 'stack tight' }, [gateNotice, list]);
      approveBtn.disabled = true;
    } else if (blocked) {
      approveBtn.disabled = true;
    }
    if (gate === 'platform_adaptations' && !exportsManifest) {
      gateNotice = C.banner('warn', 'No exports to approve', 'Generate the platform exports first.');
      approveBtn.disabled = true;
    }

    return C.panel('Approval', {
      subtitle: gate ? 'This is the gate for the finished video.' : 'Recorded against revision ' + record.revision + '.',
      children: [status || C.banner('info', 'Current state: ' + root.Stages.label(record.state), 'Generate this stage to review a result.'), gateNotice, feedback].filter(Boolean),
      footer: [changesBtn, approveBtn]
    });
  }

  /* Reads one artifact out of the loaded results, so the approval panel sees the same file the
     workspace above it is showing. */
  function readArtifact(saved, pattern) {
    var file = ((saved || {}).files || []).filter(function (item) { return pattern.test(item.path); })[0];
    if (!file || !file.content) return null;
    try { return JSON.parse(file.content); } catch (error) { return null; }
  }

  /* Preview renders are kept here rather than in the DOM, because every action ends in a refresh and
     a re-render, which would otherwise throw the player away the instant it appeared. */
  var scenePreviews = {};
  function previewKey(folder, sceneId) { return folder + '/' + sceneId; }

  /* Which scene cards are open, and which of the three paths you were using. Kept outside the render
     because a re-render rebuilds the element and `<details>` loses its open state - which happens
     after every edit, and once when the script results finish loading. That is why a card used to
     snap shut the moment you opened it or saved a template. */
  var fillState = {};
  function fillKey(folder, sceneId) { return folder + '/' + sceneId; }
  function fillFor(folder, sceneId) {
    var key = fillKey(folder, sceneId);
    if (!fillState[key]) fillState[key] = { open: false, path: null };
    return fillState[key];
  }

  /* Watchers a screen started and must stop when it is replaced. Collected per render so fourteen
     scene cards cannot each overwrite the one cleanup slot. */
  var activeWatchers = [];

  /* The Comfy status. One request per render rather than one per scene, which is the difference
     between 1 and 14 on a full storyboard, and it is re-read every time so a key added or a workflow
     file dropped in is noticed without restarting anything. A re-render is requested only when the
     answer actually changed, so renders converge instead of looping. */
  var comfyLast = {};
  var comfyPending = {};
  function comfyFor(ctx, folder) {
    if (!comfyPending[folder]) {
      comfyPending[folder] = true;
      ctx.api.comfyStatus().then(function (status) {
        comfyPending[folder] = false;
        var before = comfyLast[folder];
        comfyLast[folder] = status;
        if (!before || before.configured !== status.configured || before.workflow_ready !== status.workflow_ready) ctx.rerender();
      }).catch(function () {
        comfyPending[folder] = false;
        if (!comfyLast[folder]) {
          comfyLast[folder] = { configured: false, workflow_ready: false, workflow_problem: 'The Comfy status could not be read.' };
          ctx.rerender();
        }
      });
    }
    return comfyLast[folder] || null;
  }

  function renderPreviewPlayer(holder, folder, preview) {
    C.clear(holder);
    holder.append(el('p', { class: 'metric-note', text: 'Preview: ' + preview.template + ', ' + preview.seconds + 's, ' + preview.width + 'x' + preview.height }));
    holder.append(el('video', { class: 'asset-preview', src: root.Api.projectFileUrl(folder, preview.path), attrs: { controls: 'controls', preload: 'metadata' } }));
  }

  function renderProvider(ctx, stageId) {
    var stage = root.Stages.byId(stageId);
    var state = ctx.store.snapshot();
    var body = el('div', { class: 'stack' });
    var gate = gated(ctx, stageId);
    var compose = stageId === 'compose';
    var settings = stageId === 'research' ? researchSettings(ctx) : null;
    var record = ((ctx.store.workflow().stages) || {})[stage.server];

    if (gate) body.append(gate);
    if (settings) {
      body.append(C.panel('Generation settings', { children: settings.node }));
      body.append(connectionPanel(ctx));
    }
    if (compose) {
      body.append(C.banner('info', 'This stage produces a real video', 'The composer renders final/youtube_master.mp4 with FFmpeg and inspects the file it wrote. QC decides whether the video may be approved.'));
    }
    void 0;

    var error = state.errors[stageId];
    if (error) body.append(C.banner('error', 'Last attempt failed', error + ' Any previously saved result is unchanged.'));

    var actionLabel = compose ? 'Render the video'
      : stageId === 'final' ? 'Run the final check'
        : stageId === 'exports' ? 'Generate platform exports'
          : 'Generate ' + stage.title.toLowerCase();
    var action = button(actionLabel, {
      variant: 'primary', disabled: !!gate,
      on: async function () {
        action.setBusy(true, 'Working');
        ctx.store.setError(stageId, null);
        try {
          var body2 = stageId === 'research'
            ? { provider: settings.provider.value, web_search: settings.web.checked, include_materials: settings.materials.checked }
            : {};
          await ctx.api.generate(state.folder, stage.server, body2);
          await ctx.refresh();
          await ctx.loadResults(stage.server);
          C.toast(compose ? 'The video was rendered. Watch it, then approve it below.' : stage.title + ' saved.');
        } catch (error2) {
          ctx.store.setError(stageId, error2.message);
          C.toast(error2.message, 'error');
        } finally {
          action.setBusy(false);
          ctx.rerender();
        }
      }
    });

    var saved = state.results[stage.server];
    var content = state.resultsLoading === stage.server ? C.skeleton(4)
      : (saved ? C.resultFiles(saved)
        : C.empty('No saved result loaded', 'Generate this stage, or there is nothing saved on disk yet.'));

    // The storyboard is a plan about scenes, so it gets a scene table rather than raw files.
    if (stageId === 'storyboard' && saved) {
      var sceneTable = storyboardTable(ctx, saved);
      if (sceneTable) content = sceneTable;
      // The scene table shows the narration each scene covers, so the script must be loaded too.
      if (!state.results.script && !state.resultsAttempted.script && state.resultsLoading !== 'script') {
        ctx.loadResults('script').then(function () { ctx.rerender(); }).catch(function () { /* the table degrades to section ids */ });
      }
    }

    // Asset production is a list of real files, so it gets its own workspace.
    if (stageId === 'assets' && saved) {
      var assetsView = assetsWorkspace(ctx, saved);
      if (assetsView) content = assetsView;
    }

    /* The delivery stages show the video and its exports, so they get their own screens rather than a
       list of files. */
    if (stageId === 'compose' && saved) {
      var composeView = root.Delivery && root.Delivery.composeWorkspace(ctx, saved);
      if (composeView) content = composeView;
    }
    if (stageId === 'final' && saved) {
      var finalView = root.Delivery && root.Delivery.finalWorkspace(ctx, saved);
      if (finalView) content = finalView;
      // The final check quotes the QC verdict and the master, so both must be loaded to show them.
      if (!state.results.render && state.resultsLoading !== 'render') {
        ctx.loadResults('render').then(function () { ctx.rerender(); }).catch(function () { /* the screen degrades without it */ });
      }
    }
    if (stageId === 'exports' && saved) {
      var exportsView = root.Delivery && root.Delivery.exportsWorkspace(ctx, saved);
      if (exportsView) content = exportsView;
    }

    var savedSubtitle = stageId === 'storyboard' ? 'Scenes from the approved script, with own media selected where it fits.'
      : stageId === 'assets' ? 'What was actually produced, and what is still missing.'
        : stageId === 'compose' ? 'The video that was rendered, and what QC measured in it.'
          : stageId === 'final' ? 'The finished video, its thumbnail and the checks around it.'
            : stageId === 'exports' ? 'One file per platform, ready to upload.'
              : 'Files written into the project folder.';
    body.append(C.panel('Saved result', {
      subtitle: savedSubtitle,
      actions: action,
      children: content
    }));

    var approval = approvalPanel(ctx, stageId, record, saved);
    if (approval) body.append(approval);
    return body;
  }

  /* Narration, produced footage, and what is still missing. Every row is a real file or a real gap. */
  function assetsWorkspace(ctx, saved) {
    var file = (saved.files || []).filter(item => /asset_manifest\.json$/.test(item.path))[0];
    if (!file || !file.content) return null;
    var manifest;
    try { manifest = JSON.parse(file.content); } catch (error) { return null; }

    var wrap = el('div', { class: 'stack' });
    (manifest.warnings || []).forEach(function (warning) { wrap.append(C.banner('warn', 'Asset production', warning)); });

    var narration = manifest.narration || {};
    var counts = manifest.counts || {};
    var metrics = [
      {label: 'Narration sections', value: String(narration.produced || 0), numeric: true, note: (narration.total_seconds ? narration.total_seconds.toFixed(1) + 's of audio' : 'no audio')},
      {label: 'Your media', value: String(counts.own_media || 0), numeric: true, note: 'includes generated'},
      {label: 'Drawn locally', value: String(counts.rendered || 0), numeric: true},
      {label: 'Sourced', value: String(counts.produced || 0), numeric: true},
      {label: 'Needs media', value: String(counts.still_missing || 0), numeric: true},
      {label: 'Rights blocked', value: String(counts.rights_blocked || 0), numeric: true, note: (counts.rights_blocked ? 'cannot be rendered' : 'all clear')}
    ];
    /* Only shown when it applies. A zero here would read as a check that passed, and nothing checked
       this: the app cannot read words out of a generated picture. */
    if (counts.generated_text_unverified) {
      metrics.push({label: 'Unverified text', value: String(counts.generated_text_unverified), numeric: true, note: 'generated, nobody has read it'});
    }
    wrap.append(C.metrics(metrics));
    wrap.append(C.banner(manifest.status === 'complete' ? 'ok' : 'warn',
      manifest.status === 'complete' ? 'Every scene has media and the narration is ready' : 'This project is not ready to compose',
      manifest.status === 'complete' ? 'The composer has real media and audio to work with.' : 'Scenes without media would render as blank frames, and scenes with unrecorded rights cannot be rendered at all, so composition stays blocked until each is resolved.'));

    /* Which sources were searched, and the reason each one that was not could not be. A missing
       source is a stated cause, never an unexplained absence of footage. */
    var sourcing = manifest.sourcing;
    if (sourcing) {
      /* A saved result records what was true when it ran, so it keeps saying "no key configured" long
         after the key was saved. Left unsaid, that reads as the app ignoring the key. The recorded
         reason is compared against the live provider list, and a source that has since become usable
         is named, with the one action that fixes it. */
      var live = (ctx.store.snapshot().sourcingStatus || {}).sources || [];
      var liveIds = {};
      live.forEach(function (item) { liveIds[item.id] = true; });
      var sinceConfigured = (sourcing.unavailable || []).filter(function (item) { return liveIds[item.id]; });
      if (sinceConfigured.length) {
        var names = sinceConfigured.map(function (item) { return item.short; }).join(' and ');
        var plural = sinceConfigured.length > 1;
        wrap.append(C.banner('warn', names + (plural ? ' are' : ' is') + ' configured now',
          'This saved result was produced before ' + (plural ? 'they were' : 'it was') + ' configured, so ' +
          (plural ? 'they were' : 'it was') + ' never searched. Run Assets again to use ' + (plural ? 'them' : 'it') + '.'));
      }

      var sourcingRows = el('div', { class: 'stack tight' });
      (sourcing.sources || []).forEach(function (item) {
        sourcingRows.append(el('p', { class: 'metric-note', text: 'Searched: ' + item.short + ' (' + (item.media_kinds || []).join(', ') + ')' }));
      });
      (sourcing.unavailable || []).forEach(function (item) {
        // A source that was never consulted is a note, not a failure: nothing about this scene broke.
        sourcingRows.append(el('p', { class: 'metric-note', text: 'Not searched: ' + item.short + ' — ' + item.reason }));
      });
      if (!(sourcing.sources || []).length && !(sourcing.unavailable || []).length) sourcingRows.append(el('p', { class: 'metric-note', text: 'No media source was consulted.' }));
      wrap.append(C.panel('Where the media came from', {
        subtitle: 'Free-licence sources are tried in order. A source that could not be used says why.',
        children: sourcingRows
      }));
    }

    // Narration
    var narrationSections = (narration.sections || []);
    if (narrationSections.length) {
      var narrationPanel = el('div', { class: 'stack' });
      narrationSections.forEach(function (section) {
        var row = el('div', { class: 'stack tight' });
        var heading = el('div', { class: 'row between' }, [
          el('strong', { text: section.title || section.section_id }),
          C.pill(section.status === 'done' ? 'approved' : (section.status === 'failed' ? 'failed' : 'review'))
        ]);
        row.append(heading);
        if (section.status === 'done') {
          row.append(el('p', { class: 'metric-note', text: [section.duration_seconds ? section.duration_seconds.toFixed(1) + 's' : 'duration unknown', section.characters + ' characters', section.model, section.voice].filter(Boolean).join(' | ') }));
          row.append(el('audio', { class: 'asset-preview-audio', src: root.Api.projectFileUrl(ctx.store.snapshot().folder, section.path), attrs: {controls: 'controls', preload: 'none'}, props: {style: 'width:100%'} }));
        } else {
          row.append(el('p', { class: 'field-error', text: section.reason || 'No audio was produced for this section.' }));
        }
        narrationPanel.append(row);
      });
      wrap.append(C.panel('Narration', { subtitle: 'One audio file per script section, with the duration measured from the file itself.', children: narrationPanel }));
    }

    // Scenes
    var table = el('table', { class: 'table' });
    table.append(el('thead', {}, el('tr', {}, [el('th', { text: 'Scene' }), el('th', { text: 'Media' }), el('th', { text: 'Source' })])));
    var body2 = el('tbody');
    (manifest.scenes || []).forEach(function (scene) {
      var pill = scene.status === 'own_media' ? C.pill('approved')
        : scene.status === 'produced' ? C.pill('ok')
          : scene.status === 'failed' ? C.pill('failed') : C.pill('review');
      var sourceCell;
      // The rights verdict travels with the scene, so the interface shows the real decision.
      var rightsState = scene.rights_state || null;
      var rightsLines = [];
      if (rightsState) {
        if (rightsState.state === 'blocked') rightsLines.push(el('p', { class: 'field-error', text: (rightsState.reasons || [])[0] || 'Rights are not cleared for this scene.' }));
        else if (rightsState.attribution) rightsLines.push(el('p', { class: 'metric-note', text: 'Credit: ' + rightsState.attribution }));
        else rightsLines.push(el('p', { class: 'metric-note', text: 'Rights: ' + (rightsState.short || 'cleared') }));
      }
      if (scene.status === 'own_media') {
        /* A generated file is attached to the scene exactly like own media, and the gate clears it the
           same way, but it is not something the operator filmed, so it is not labelled as if it were. */
        var generated = scene.origin === 'generated';
        var holder = scene.rights && scene.rights.holder ? ' with ' + scene.rights.holder : '';
        sourceCell = el('div', { class: 'stack tight' }, [
          el('p', { class: 'metric-note', text: generated ? 'Generated' + holder + ', then attached to this scene.' : 'Your own material' })
        ].concat(rightsLines));
      } else if (scene.status === 'produced') {
        sourceCell = el('div', { class: 'stack tight' }, [
          el('p', { class: 'metric-note', text: (scene.clip.provider || 'stock') + (scene.clip.author ? ' | ' + scene.clip.author : '') + (scene.clip.media_kind === 'image' ? ' | still image' : '') }),
          el('p', { class: 'metric-note', text: scene.clip.licence || '' })
        ].concat(rightsLines).concat([
          scene.clip.source_url ? el('a', { class: 'mono', href: scene.clip.source_url, text: 'Source clip', attrs: {target: '_blank', rel: 'noopener noreferrer'}}) : null
        ]));
      } else if (scene.status === 'rendered') {
        /* Drawn here by our own code from the project's own script. No source was ever consulted, so
           this scene has no licence question and must not be shown one. */
        sourceCell = el('div', { class: 'stack tight' }, [
          el('p', { class: 'metric-note', text: 'Drawn locally as ' + (scene.template || 'a template') + '. No external source.' })
        ].concat(rightsLines));
      } else {
        /* Which source was asked and which was never consulted. The concatenated sentence is the
           fallback, not the main event: "no key configured" is not the same problem as "nothing
           matched", and only the first is something you can fix.
           The headline accuses the sources only when the sources were actually asked. A template
           missing its data, and a scene nobody has chosen a path for, are not licence outcomes, and
           telling the operator "no free-licence media matched" for them was simply untrue. */
        var attempts = scene.sourced_after || [];
        var waiting = scene.status === 'skipped';
        var headline = waiting ? 'No media chosen for this scene yet.'
          : attempts.length ? 'No media found for this scene.'
            : 'This scene could not be produced.';
        sourceCell = el('div', { class: 'stack tight' }, [el('p', { class: waiting ? 'metric-note' : 'field-error', text: headline })]);
        attempts.forEach(function (item) {
          sourceCell.append(el('p', { class: 'metric-note', text: item.short + ' — searched, ' + item.reason }));
        });
        /* Only a scene that was going to be sourced is told which sources were unavailable. A scene
           with a template never goes near a stock provider, so listing Pexels under a diagram that is
           missing its data describes a step that was never part of this scene. */
        if (!scene.template) {
          ((sourcing && sourcing.unavailable) || []).forEach(function (item) {
            sourceCell.append(el('p', { class: 'metric-note', text: item.short + ' — not searched: ' + item.reason }));
          });
        }
        if (!attempts.length && scene.reason) sourceCell.append(el('p', { class: 'metric-note', text: scene.reason }));
        if (scene.query) sourceCell.append(el('p', { class: 'metric-note mono', text: 'Searched for: ' + scene.query }));
      }
      body2.append(el('tr', {}, [
        el('td', {}, [el('strong', { text: scene.title || scene.scene_id }), el('p', { class: 'metric-note mono', text: scene.scene_id })]),
        el('td', {}, [pill, el('p', { class: 'metric-note', text: scene.seconds ? scene.seconds + 's needed' : '' })]),
        el('td', {}, sourceCell)
      ]));
    });
    table.append(body2);
    wrap.append(C.panel('Scenes', { children: table, class: 'flush' }));

    var details = el('details');
    details.append(el('summary', { text: 'Supporting files' }));
    details.append(C.resultFiles(saved));
    wrap.append(details);
    return wrap;
  }

  /* The storyboard is a plan about scenes, so it shows the scenes themselves: one card each, and the
     three ways of filling a scene behind a button rather than all on screen at once.
     A card remembers whether it is open and which path you were on, because a re-render rebuilds it. */
  function storyboardTable(ctx, saved) {
    var file = (saved.files || []).filter(item => /storyboard\.json$/.test(item.path))[0];
    if (!file || !file.content) return null;
    var parsed;
    try { parsed = JSON.parse(file.content); } catch (error) { return null; }
    var scenes = Array.isArray(parsed.scenes) ? parsed.scenes : [];
    if (!scenes.length) return null;

    var folder = ctx.store.snapshot().folder;
    var library = {};
    ctx.store.snapshot().library.forEach(function (asset) { library[asset.id] = asset; });

    var scripts = ctx.store.snapshot().results.script;
    var narration = {};
    if (scripts) {
      var scriptFile = (scripts.files || []).filter(item => /script\.json$/.test(item.path))[0];
      if (scriptFile && scriptFile.content) {
        try {
          JSON.parse(scriptFile.content).sections.forEach(function (section) { narration[section.id] = section; });
        } catch (error) { /* leave narration empty */ }
      }
    }

    /* The prompt pack and the template vocabulary come from the server, so the cards use its own names
       rather than a list invented here. */
    var packFile = (saved.files || []).filter(function (item) { return /scene_prompts\.json$/.test(item.path); })[0];
    var pack = null;
    if (packFile && packFile.content) { try { pack = JSON.parse(packFile.content); } catch (error) { pack = null; } }
    var promptsById = {};
    if (pack && Array.isArray(pack.prompts)) pack.prompts.forEach(function (item) { promptsById[item.scene_id] = item; });
    var templates = ((ctx.store.snapshot().renderTemplates || {}).templates) || [];

    var comfy = comfyFor(ctx, folder);
    activeWatchers = [];

    var wrap = el('div', { class: 'stack' });
    if (parsed.warnings && parsed.warnings.length) {
      parsed.warnings.forEach(function (warning) { wrap.append(C.banner('warn', 'Storyboard warning', warning)); });
    }

    /* One vocabulary for one thing. A scene used to be "Missing" in the table, "Not filled" on the
       card and "Still to produce" in the metrics, which read as three different problems. */
    function stateOf(scene) {
      if (scene.asset_id) {
        var asset = library[scene.asset_id];
        var name = asset ? asset.name : 'Asset ' + scene.asset_id;
        var generated = !!(scene.attachment && scene.attachment.rights_basis === 'generated');
        var from = scene.attachment && scene.attachment.provider ? ' (from ' + scene.attachment.provider + ')' : '';
        return {
          id: generated ? 'generated' : 'your_media',
          label: generated ? 'Generated' : 'Your media',
          tone: 'ok',
          note: (generated ? 'Generated file: ' : 'Your own media: ') + name + from + '.'
        };
      }
      if (scene.graphic_template) {
        /* A template the app substituted because the assigned one could not be filled says so, and
           names what it replaced. Shown as a note rather than as a problem: the scene renders, and
           the picker below changes it back in one click. */
        if (scene.template_auto) {
          return {
            id: 'drawn', label: 'Drawn locally', tone: 'review',
            note: 'Drawn locally as ' + scene.graphic_template + '. '
              + (scene.template_from || 'The assigned template') + ' could not be filled: '
              + (scene.template_reason || 'its data was missing')
              + ' The scene renders from its own words. Give it real figures below to get that picture back.'
          };
        }
        return { id: 'drawn', label: 'Drawn locally', tone: 'info', note: 'Drawn locally as ' + scene.graphic_template + ', which is free and spells your words exactly.' };
      }
      return { id: 'needs', label: 'Needs media', tone: 'review', note: 'Nothing is chosen for this scene yet. Pick one of the three ways below.' };
    }
    function statePill(tone, text) { return el('span', { class: 'pill ' + tone, text: text }); }

    var withMedia = scenes.filter(function (scene) { return !!scene.asset_id; }).length;
    var drawnCount = scenes.filter(function (scene) { return !scene.asset_id && !!scene.graphic_template; }).length;
    var needsCount = scenes.length - withMedia - drawnCount;
    wrap.append(C.metrics([
      { label: 'Scenes', value: String(scenes.length), numeric: true },
      { label: 'Your media', value: String(withMedia), numeric: true, note: 'includes generated' },
      { label: 'Drawn locally', value: String(drawnCount), numeric: true },
      { label: 'Needs media', value: String(needsCount), numeric: true, note: needsCount ? 'cannot be rendered yet' : 'all clear' },
      { label: 'Total', value: (parsed.total_duration_seconds || 0) + 's', numeric: true }
    ]));

    function runWith(control, label, work) {
      if (control && control.setBusy) control.setBusy(true, label);
      return Promise.resolve()
        .then(work)
        .catch(function (error) { C.toast(error.message, 'error'); })
        .then(function () { if (control && control.setBusy) control.setBusy(false); })
        .then(function () { return ctx.refresh(); })
        // The saved result is cached, so an edit would otherwise leave the old plan on screen.
        .then(function () { return ctx.loadResults('storyboard'); })
        .then(function () { ctx.rerender(); })
        .catch(function (error) { C.toast(error.message, 'error'); });
    }

    /* Only material already chosen for this project. Listing the whole library offered files this
       project has nothing to do with, which is why an empty selection still showed a stray file. */
    function projectMaterial() {
      var project = ctx.store.project() || {};
      var selections = (((project.workflow || {}).materials || {}).selections) || [];
      var chosen = {};
      selections.filter(function (item) { return item.decision === 'use'; })
        .forEach(function (item) { chosen[item.asset_id] = true; });
      return Object.keys(library).map(function (id) { return library[id]; }).filter(function (asset) {
        return chosen[asset.id] && asset.publishable !== false && C.rightsState(asset).state !== 'blocked';
      });
    }

    /* ---------- the three ways to fill a scene ---------- */

    function localPanel(scene) {
      var node = el('div', { class: 'stack tight', attrs: { 'data-panel': 'local' } });
      if (scene.asset_id) {
        node.append(C.banner('info', 'This scene already uses your own media',
          'Detach it first if you want it drawn locally instead. Use a file has the detach control.'));
        return { node: node };
      }
      var assigned = scene.graphic_template || null;
      var entry = promptsById[scene.id] || {};
      var templateSelect = C.select({ id: 'template-' + scene.id, value: assigned || entry.suggested_template || templates[0] }, templates.map(function (name) {
        return { value: name, label: name };
      }));
      var dataBox = C.textArea({ id: 'data-' + scene.id, rows: 4, placeholder: 'The data this template needs, as JSON.' });
      dataBox.value = scene.graphic_data ? JSON.stringify(scene.graphic_data, null, 2) : '';
      var previewHolder = el('div');

      var assign = button(assigned ? 'Save template and data' : 'Draw with this template', { size: 'sm', variant: 'primary', on: function () {
        var data = null;
        var raw = String(dataBox.value || '').trim();
        if (raw) {
          try { data = JSON.parse(raw); }
          catch (error) { C.toast('The data is not valid JSON: ' + error.message, 'error'); return; }
        }
        runWith(assign, 'Saving', function () {
          return ctx.api.assignGraphic(folder, scene.id, templateSelect.value, data).then(function (result) {
            if (result.artifact.needs_data) C.toast('Template saved. It still needs data: ' + result.artifact.data_problem, 'error');
            else C.toast('This scene will be drawn as ' + templateSelect.value + '.');
          });
        });
      } });
      var clear = button('Clear', { size: 'sm', disabled: !assigned, on: function () {
        runWith(clear, 'Clearing', function () {
          return ctx.api.assignGraphic(folder, scene.id, null).then(function () { C.toast('Cleared. This scene needs media again.'); });
        });
      } });
      var preview = button('Render preview', { size: 'sm', on: function () {
        var data = null;
        var raw = String(dataBox.value || '').trim();
        if (raw) { try { data = JSON.parse(raw); } catch (error) { C.toast('The data is not valid JSON: ' + error.message, 'error'); return; } }
        runWith(preview, 'Drawing', function () {
          return ctx.api.renderPreview(folder, scene.id, { template: templateSelect.value, data: data }).then(function (result) {
            scenePreviews[previewKey(folder, scene.id)] = result.preview;
            renderPreviewPlayer(previewHolder, folder, result.preview);
            C.toast('Preview drawn. It is not part of the plan until you save the template.');
          });
        });
      } });
      var storedPreview = scenePreviews[previewKey(folder, scene.id)];
      if (storedPreview) renderPreviewPlayer(previewHolder, folder, storedPreview);

      node.append(C.field('Template', templateSelect, { hint: 'A drawing is free, offline, and spells your words exactly. Assigning changes the storyboard, so it needs approval again.' }));
      node.append(C.field('Data for that template', dataBox, { hint: 'Assigning fills in a starting point where one can be derived; nothing is invented. A chart needs real figures.' }));
      node.append(el('div', { class: 'row' }, [assign, preview, clear]));
      node.append(previewHolder);
      return { node: node };
    }

    function generatePanel(scene) {
      var node = el('div', { class: 'stack tight', attrs: { 'data-panel': 'generate' } });
      /* The caution belongs in the path where the decision is made, and it is about the scene rather
         than about Comfy, so it is shown whatever state the provider is in. */
      var entry = promptsById[scene.id] || {};
      if (entry.typographic) {
        /* This used to say a generator "will misspell these words", which was a claim the app could
           not support and could not check. It is now what is actually known: models this size render
           words from what they have seen rather than by spelling them, technical names are the worst
           case, and nothing here can read the picture back to see whether it worked. */
        node.append(C.banner('warn', 'Mostly on-screen text',
          'Comfy renders these words as pixels, not as spelling: a model reproduces text it has seen '
          + 'before, so an unusual name like "Dora-rs" or "LeRobot" can come out misspelled or invented. '
          + 'This app has no way to read the words back out of a generated picture, so it cannot check '
          + 'the result for you. Drawing it locally spells them exactly. Test the workflow below if you '
          + 'want to find out how it does with these specific words.'));
      }
      if (!comfy) {
        node.append(el('p', { class: 'metric-note', text: 'Checking the Comfy configuration...' }));
        return { node: node };
      }
      if (!comfy.configured) {
        node.append(C.banner('warn', 'Add a Comfy API key to generate a scene',
          'Settings stores the key; the workflow you export from ComfyUI goes in ' + (comfy.workflow_config_path || 'projects/_settings/comfy/workflows.json') + '. The other two paths still work.'));
        return { node: node };
      }
      if (!comfy.workflow_ready) {
        node.append(C.banner('warn', 'No exported workflow is in place',
          comfy.workflow_problem || 'Export your ComfyUI workflow with Workflow then Export (API) and save it beside workflows.json.'));
        return { node: node };
      }

      /* The text probe is offered before the scene's own path is considered, because it is a question
         about the workflow rather than about this scene: a scene drawn locally can still be the source
         of the words worth testing. Every return below carries its onShow, or a panel that returns
         early would show the probe and never load it. */
      var probe = textProbeBlock(scene);
      if (probe) node.append(probe.node);
      function withProbe() {
        return { node: node, onShow: function () { if (probe) probe.onShow(); } };
      }

      if (scene.asset_id) {
        node.append(C.banner('info', 'This scene already uses your own media',
          'Detach it first if you want to generate a replacement. Use a file has the detach control.'));
        return withProbe();
      }
      if (scene.graphic_template) {
        node.append(C.banner('info', 'This scene is drawn locally',
          'It is assigned the ' + scene.graphic_template + ' template, which is free. Clear that in Draw locally first if you want to generate instead.'));
        return withProbe();
      }

      var statusLine = el('p', { class: 'metric-note', text: 'Checking this scene...' });
      var controls = el('div', { class: 'stack tight' });
      var generation = null;
      var mounted = false;
      var timer = null;
      var cancelled = false;
      function stopWatching() { cancelled = true; if (timer) { clearTimeout(timer); timer = null; } }

      node.append(statusLine);
      node.append(controls);
      function paint() {
        C.clear(controls);
        var running = generation && generation.active ? generation.active : null;
        if (running) {
          statusLine.textContent = 'Generating with ' + running.workflow + ': ' + root.Stages.label(running.status)
            + (running.progress && typeof running.progress.value === 'number' ? ' (' + Math.round(running.progress.value * 100) + '%)' : '')
            + '. This continues if you leave the page.';
          var cancelBtn = button('Cancel the generation', { on: function () {
            cancelBtn.setBusy(true, 'Cancelling');
            ctx.api.cancelGeneration(folder, scene.id, running.job_id).then(function () { return load(); })
              .catch(function (error) { C.toast(error.message, 'error'); })
              .finally(function () { cancelBtn.setBusy(false); });
          } });
          controls.append(el('div', { class: 'row' }, [cancelBtn]));
          return;
        }
        if (generation && generation.imported_asset_id) statusLine.textContent = 'A generated file is attached to this scene.';
        else if (generation && generation.last_error) {
          statusLine.textContent = 'The last generation did not produce a file.';
          controls.append(C.banner('warn', 'The last generation failed', generation.last_error));
        } else statusLine.textContent = 'Nothing has been generated for this scene yet.';

        var workflows = comfy.workflows || [];
        var workflowSelect = C.select({ id: 'comfy-workflow-' + scene.id, value: comfy.default_workflow || (workflows[0] ? workflows[0].name : '') },
          workflows.map(function (item) { return { value: item.name, label: item.name + ' (' + item.output + ')' }; }));
        var prompt = C.textArea({ id: 'comfy-prompt-' + scene.id, rows: 3, placeholder: 'Describe the shot for the generator.' });
        prompt.value = scene.generation_prompt || scene.visual_intent || '';
        var generateBtn = button('Generate this scene', { variant: 'primary', on: function () {
          generateBtn.setBusy(true, 'Submitting');
          ctx.api.generateScene(folder, scene.id, { workflow: workflowSelect.value, prompt: prompt.value }).then(function (result) {
            C.toast('Generation submitted. It costs Comfy credits and takes a few minutes.');
            generation = { active: { job_id: result.job.job_id, status: result.job.status, workflow: result.job.workflow, progress: null } };
            paint();
            watch(result.job.job_id);
          }).catch(function (error) {
            C.toast(error.message, 'error');
          }).finally(function () { generateBtn.setBusy(false); });
        } });
        generateBtn.disabled = !String(prompt.value || '').trim();
        prompt.addEventListener('input', function () { generateBtn.disabled = !String(prompt.value || '').trim(); });

        controls.append(C.field('Workflow', workflowSelect, { hint: 'Each one is a workflow you exported from ComfyUI. Video costs more credits than an image.' }));
        controls.append(C.field('Prompt', prompt, { hint: 'Sent to the node named in workflows.json. Edit it here without changing the storyboard.' }));
        controls.append(el('div', { class: 'row' }, [
          generateBtn,
          button('Copy prompt', { size: 'sm', on: function () {
            C.copyText(prompt.value).then(function (how) { if (how === 'copied') C.toast('Prompt copied.'); });
          } })
        ]));
        if (!String(prompt.value || '').trim()) {
          controls.append(C.banner('warn', 'This scene has no prompt', 'Write one above, or generate the storyboard again so it writes one.'));
        }
        controls.append(el('p', { class: 'metric-note', text: 'A run costs Comfy credits and takes minutes. The result is imported as your own generated work and attached to this scene.' }));
      }

      /* Polls the server, which polls Comfy. Deliberately slow: a GPU job runs for minutes. */
      function watch(jobId) {
        if (cancelled) return;
        ctx.api.generationStatus(folder, scene.id, jobId).then(function (result) {
          if (cancelled) return;
          var job = result.job || {};
          generation = {
            active: result.done ? null : { job_id: jobId, status: job.status, workflow: job.workflow, progress: job.progress },
            imported_asset_id: result.attached_asset_id || (generation && generation.imported_asset_id),
            last_error: job.error || null
          };
          if (result.attached_asset_id) {
            C.toast('The scene was generated and attached.');
            ctx.loadResults('storyboard').then(function () { ctx.rerender(); });
            return;
          }
          if (result.done) { paint(); return; }
          paint();
          timer = setTimeout(function () { watch(jobId); }, 4000);
        }).catch(function (error) {
          if (cancelled) return;
          statusLine.textContent = error.message;
          C.toast(error.message, 'error');
        });
      }

      function load() {
        return ctx.api.sceneGeneration(folder, scene.id).then(function (result) {
          generation = result.generation;
          paint();
          if (generation && generation.active) watch(generation.active.job_id);
        }).catch(function (error) { statusLine.textContent = error.message; });
      }

      return {
        node: node,
        // Mounted when you open this path, so a fourteen-scene screen makes one request, not fourteen.
        onShow: function () {
          if (probe) probe.onShow();
          if (mounted) return;
          mounted = true;
          activeWatchers.push(stopWatching);
          load();
        }
      };
    }

    /* One question the app cannot answer for itself: can the workflow you configured actually spell
       these words? It cannot read a picture back, so it asks you, once, with a single cheap image
       whose subject is the scene's own on-screen text. The answer is remembered against the workflow,
       because that is what it is about - every other scene on the same workflow inherits it. */
    function textProbeBlock(scene) {
      // Only text the scene actually puts on screen: a title is not drawn into the picture.
      var words = String(scene.on_screen_text || '').trim();
      if (!words) return null;
      var node = el('div', { class: 'stack tight', attrs: { 'data-panel': 'probe' } });
      var summary = el('p', { class: 'metric-note', text: 'Nobody has tested this workflow on words like these yet.' });
      var holder = el('div', { class: 'stack tight' });
      var state = null;
      var mounted = false;
      var timer = null;
      var stopped = false;
      var watching = null;
      function stopWatching() { stopped = true; if (timer) { clearTimeout(timer); timer = null; } }

      function paint() {
        C.clear(holder);
        var last = state && state.probe ? state.probe : null;
        var known = state && state.verdict ? state.verdict : null;
        if (known && known.judged_at) {
          summary.textContent = known.verdict === 'correct'
            ? 'You tested workflow "' + known.workflow + '" on ' + String(known.judged_at).slice(0, 10) + ': the words came out correctly.'
            : 'You tested workflow "' + known.workflow + '" on ' + String(known.judged_at).slice(0, 10) + ': the words did not come out correctly. Drawing locally spells them exactly.';
        } else {
          summary.textContent = 'Nobody has tested this workflow on words like these yet.';
        }
        if (watching) {
          holder.append(el('p', { class: 'metric-note', text: 'Generating a test image with ' + watching.workflow + ': ' + root.Stages.label(watching.status) + '.' }));
          return;
        }
        if (last && last.asset_id) {
          holder.append(el('img', { class: 'asset-preview', src: root.Api.fileUrl(last.asset_id), attrs: { alt: 'Text probe for ' + words, loading: 'lazy' } }));
          if (last.verdict) {
            holder.append(el('p', { class: 'metric-note', text: (last.verdict === 'correct' ? 'You judged these words correct.' : 'You judged these words incorrect.') + ' Tested with "' + last.workflow + '".' }));
          } else {
            holder.append(el('p', { class: 'metric-note', text: 'Look at the image: are these words spelled correctly? Your answer is remembered for this workflow.' }));
            var yes = button('The words are correct', { size: 'sm', on: function () { judge(yes, true); } });
            var no = button('The words are wrong', { size: 'sm', on: function () { judge(no, false); } });
            holder.append(el('div', { class: 'row' }, [yes, no]));
          }
        } else if (last && last.failed) {
          holder.append(C.banner('warn', 'The test image was not produced', 'The generation did not succeed, so nothing was learned about spelling. Try again, or draw the scene locally.'));
        }
        var run = button('Generate a test image', { size: 'sm', on: function () {
          run.setBusy(true, 'Submitting');
          ctx.api.textProbe(folder, scene.id, {}).then(function (result) {
            watching = { job_id: result.job.job_id, workflow: result.job.workflow, status: result.job.status };
            C.toast('Test image submitted. It costs one Comfy run.');
            paint();
            watch(result.job.job_id);
          }).catch(function (error) { C.toast(error.message, 'error'); }).finally(function () { run.setBusy(false); });
        } });
        holder.append(el('div', { class: 'row' }, [run]));
        holder.append(el('p', { class: 'metric-note', text: 'One image, sent to the workflow above. It is kept in the library and is never attached to this scene.' }));
      }

      function judge(control, correct) {
        if (!state || !state.probe) return;
        control.setBusy(true, 'Saving');
        ctx.api.textProbeVerdict(folder, state.probe.probe_id, { spelled_correctly: correct }).then(function () {
          C.toast(correct ? 'Recorded: this workflow spells these words correctly.' : 'Recorded: this workflow does not spell these words correctly.');
          return load();
        }).catch(function (error) { C.toast(error.message, 'error'); }).finally(function () { control.setBusy(false); });
      }

      function watch(jobId) {
        if (stopped) return;
        ctx.api.generationStatus(folder, scene.id, jobId).then(function (result) {
          if (stopped) return;
          var job = result.job || {};
          if (result.done) {
            watching = null;
            if (job.status === 'failed' || job.error) C.toast(job.error || 'The test image failed.', 'error');
            return load();
          }
          watching = { job_id: jobId, workflow: job.workflow, status: job.status };
          paint();
          timer = setTimeout(function () { watch(jobId); }, 4000);
        }).catch(function (error) {
          if (stopped) return;
          watching = null;
          summary.textContent = error.message;
          paint();
        });
      }

      function load() {
        return ctx.api.sceneGeneration(folder, scene.id).then(function (result) {
          state = result.text_probe || null;
          paint();
        }).catch(function (error) { summary.textContent = error.message; });
      }

      node.append(C.panel('Can this workflow spell these words?', {
        subtitle: 'The app cannot read a generated picture, so it cannot check. This asks you once, with the words this scene actually puts on screen.',
        children: el('div', { class: 'stack tight' }, [summary, holder])
      }));
      return {
        node: node,
        onShow: function () {
          if (mounted) return;
          mounted = true;
          activeWatchers.push(stopWatching);
          load();
        }
      };
    }

    function attachPanel(scene) {
      var node = el('div', { class: 'stack tight', attrs: { 'data-panel': 'attach' } });
      if (scene.graphic_template) {
        node.append(C.banner('info', 'This scene is drawn locally',
          'It is assigned the ' + scene.graphic_template + ' template, which is free. Clear that in Draw locally first if you want to use a file instead.'));
        return { node: node };
      }
      var eligible = projectMaterial();
      var attachSelect = C.select({ id: 'attach-' + scene.id, value: eligible.length ? eligible[0].id : '' }, eligible.map(function (asset) {
        return { value: asset.id, label: asset.name };
      }));
      var attachBtn = button('Attach to this scene', { size: 'sm', disabled: !eligible.length, on: function () {
        runWith(attachBtn, 'Attaching', function () {
          return ctx.api.attachSceneAsset(folder, scene.id, { asset_id: attachSelect.value }).then(function () { C.toast('Attached.'); });
        });
      } });
      node.append(C.field('Material chosen for this project', attachSelect, {
        hint: eligible.length
          ? 'Attaching replaces whatever this scene uses now.'
          : 'Nothing is chosen for this project yet. Mark files as Use in Own material, and they appear here.'
      }));
      node.append(el('div', { class: 'row' }, [attachBtn]));

      if (scene.asset_id) {
        var detach = button('Detach this scene', { size: 'sm', on: function () {
          runWith(detach, 'Detaching', function () {
            return ctx.api.attachSceneAsset(folder, scene.id, { asset_id: null }).then(function () { C.toast('Detached. This scene needs media again.'); });
          });
        } });
        node.append(el('div', { class: 'row' }, [detach]));
      }

      var fileInput = el('input', { type: 'file', id: 'attach-file-' + scene.id, attrs: { 'aria-label': 'Choose a generated file to attach' } });
      fileInput.addEventListener('change', function (event) {
        var chosen = (event.target.files || [])[0];
        if (!chosen) return;
        event.target.value = '';
        runWith(fileInput, 'Uploading', function () {
          return ctx.api.upload(chosen, 'media').then(function (uploaded) {
            var assetId = uploaded.asset.id;
            // Rights are recorded before attaching, because the gate will refuse an unrecorded file.
            return new Promise(function (resolve) {
              C.rightsDialog({
                subject: chosen.name,
                licences: ctx.store.snapshot().licences || [],
                rights: { basis: 'generated' },
                onSave: function (rights) {
                  return ctx.api.setAssetRights(assetId, rights).then(function () {
                    return ctx.api.attachSceneAsset(folder, scene.id, { asset_id: assetId, tool: rights.holder, note: rights.note });
                  }).then(function () { C.toast('Uploaded, recorded and attached to ' + scene.id + '.'); resolve(true); });
                },
                onCancel: function () { C.toast('The file is in the library but was not attached.', 'error'); resolve(false); }
              });
            });
          });
        });
      });
      node.append(C.field('Or upload a file you generated', fileInput, { hint: 'Uploading asks for a licence basis first, because attaching an unrecorded file would be refused.' }));
      return { node: node };
    }

    function sceneCard(scene) {
      var state = stateOf(scene);
      var entry = promptsById[scene.id] || {};
      var store = fillFor(folder, scene.id);
      var detail = el('details', { class: 'fill-scene', attrs: { 'data-scene': scene.id, 'data-state': state.id } });
      detail.open = !!store.open;
      detail.addEventListener('toggle', function () { store.open = detail.open; });

      detail.append(el('summary', {}, [
        el('strong', { text: scene.title || scene.id }),
        el('span', { class: 'metric-note', text: ' ' + (scene.seconds || 0) + 's' }),
        statePill(state.tone, state.label),
        entry.typographic ? el('span', { class: 'metric-note', text: ' · mostly on-screen text' }) : null
      ]));

      var body = el('div', { class: 'stack tight' });
      detail.append(body);
      body.append(el('p', { class: 'metric-note', text: state.note }));

      var section = scene.narration_section_id ? narration[scene.narration_section_id] : null;
      if (section && section.narration) body.append(el('div', { class: 'asset-excerpt', text: String(section.narration).slice(0, 400) }));
      var meta = [scene.shot_type, scene.visual_intent].filter(Boolean).join(' | ');
      if (meta) body.append(el('p', { class: 'metric-note', text: meta }));
      if (scene.on_screen_text) body.append(el('p', { class: 'metric-note', text: 'On screen: ' + scene.on_screen_text }));

      var panels = { local: localPanel(scene), generate: generatePanel(scene), attach: attachPanel(scene) };
      var paths = ['local', 'generate', 'attach'];

      function apply(path) {
        detail.setAttribute('data-path', path || '');
        paths.forEach(function (key) {
          panels[key].node.hidden = key !== path;
          buttons[key].setAttribute('aria-pressed', String(key === path));
        });
        if (path && panels[path].onShow) panels[path].onShow();
      }
      function toggle(path) { store.path = store.path === path ? null : path; apply(store.path); }

      var buttons = {
        local: button('Draw locally', { size: 'sm', dataset: { path: 'local' }, on: function () { toggle('local'); } }),
        generate: button('Generate with Comfy', { size: 'sm', dataset: { path: 'generate' }, on: function () { toggle('generate'); } }),
        attach: button('Use a file', { size: 'sm', dataset: { path: 'attach' }, on: function () { toggle('attach'); } })
      };
      body.append(el('div', { class: 'row' }, [buttons.local, buttons.generate, buttons.attach]));
      paths.forEach(function (key) { body.append(panels[key].node); });

      // Restores whichever panel you were using, without toggling it off.
      apply(store.path);
      return detail;
    }

    var cardStack = el('div', { class: 'stack tight' });
    scenes.forEach(function (scene) { cardStack.append(sceneCard(scene)); });
    wrap.append(C.panel('Scenes', {
      subtitle: 'Every scene, and the three ways to fill one. Drawing is free and offline; generating costs Comfy credits; using a file attaches something you already have.',
      children: cardStack
    }));

    var details = el('details');
    details.append(el('summary', { text: 'Supporting files' }));
    details.append(C.resultFiles(saved));
    wrap.append(details);

    /* Every watcher this screen started, stopped together when it is replaced. */
    ctx.onLeave = function () {
      var watchers = activeWatchers;
      activeWatchers = [];
      watchers.forEach(function (stop) { try { stop(); } catch (error) { /* nothing left to stop */ } });
    };
    return wrap;
  }

  function render(ctx, stageId) {
    return renderProvider(ctx, stageId);
  }

  Views.stage = {
    render: render,
    meta: function (stageId) {
      var stage = root.Stages.byId(stageId);
      return {
        title: stage.title,
        eyebrow: 'Stage ' + (root.Stages.indexOf(stageId) + 1) + ' of ' + root.Stages.STAGES.length,
        subtitle: stage.summary
      };
    }
  };
})(window);
